### ISSUE TITLE
Loss of connection, in windows  

### ISSUE THREAD

**Issue by kalekoi** [Achi-Coin/achi-blockchain#17]
I lose connection, and adding them manually doesn't work. I send you part of the log with the errors.
It happened about two weeks ago, before it worked correctly.

2021-11-02T16:18:02.870 wallet achi.wallet.wallet_blockchain: ERROR    Error during db transaction: Cannot operate on a closed database.
2021-11-02T16:18:02.871 wallet wallet_server              : ERROR    Exception: Cannot operate on a closed database., None. Traceback (most recent call last):
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\wallet\wallet_node_api.py", line 49, in new_peak_wallet
  File "achi\wallet\wallet_node.py", line 441, in new_peak_wallet
  File "achi\wallet\wallet_node.py", line 392, in complete_blocks
  File "achi\wallet\wallet_blockchain.py", line 227, in receive_block
  File "achi\wallet\wallet_block_store.py", line 90, in add_block_record
  File "aiosqlite\cursor.py", line 69, in close
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.ProgrammingError: Cannot operate on a closed database.

2021-11-02T16:18:02.872 wallet wallet_server              : ERROR    Exception: Cannot operate on a closed database. <class 'sqlite3.ProgrammingError'>, closing connection None. Traceback (most recent call last):
  File "achi\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "achi\server\server.py", line 533, in wrapped_coroutine
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\wallet\wallet_node_api.py", line 49, in new_peak_wallet
  File "achi\wallet\wallet_node.py", line 441, in new_peak_wallet
  File "achi\wallet\wallet_node.py", line 392, in complete_blocks
  File "achi\wallet\wallet_blockchain.py", line 227, in receive_block
  File "achi\wallet\wallet_block_store.py", line 90, in add_block_record
  File "aiosqlite\cursor.py", line 69, in close
  File "aiosqlite\cursor.py", line 31, in _execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.ProgrammingError: Cannot operate on a closed database.

2021-11-02T17:34:40.951 full_node full_node_server        : ERROR    Exception: Failed to fetch block 392480 from {'host': '45.148.28.44', 'port': 9975}, timed out, {'host': '45.148.28.44', 'port': 9975}. Traceback (most recent call last):
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 392480 from {'host': '45.148.28.44', 'port': 9975}, timed out

2021-11-02T17:34:40.953 full_node full_node_server        : ERROR    Exception: Failed to fetch block 392480 from {'host': '45.148.28.44', 'port': 9975}, timed out <class 'ValueError'>, closing connection {'host': '45.148.28.44', 'port': 9975}. Traceback (most recent call last):
  File "achi\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "achi\server\server.py", line 533, in wrapped_coroutine
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 392480 from {'host': '45.148.28.44', 'port': 9975}, timed out

2021-11-02T17:34:50.946 full_node full_node_server        : WARNING  Banning 45.148.28.44 for 10 seconds
2021-11-02T17:59:58.496 full_node full_node_server        : WARNING  Cannot write to closing transport 45.148.28.43
2021-11-02T20:56:04.700 full_node full_node_server        : WARNING  Cannot write to closing transport 170.249.236.102
2021-11-03T01:50:24.245 full_node full_node_server        : ERROR    Exception: Failed to fetch block 394063 from None, timed out, None. Traceback (most recent call last):
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 394063 from None, timed out

2021-11-03T01:50:24.249 full_node full_node_server        : ERROR    Exception: Failed to fetch block 394063 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "achi\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "achi\server\server.py", line 533, in wrapped_coroutine
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 394063 from None, timed out

2021-11-03T01:50:24.251 full_node full_node_server        : ERROR    Exception: Failed to fetch block 394064 from None, timed out, None. Traceback (most recent call last):
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 394064 from None, timed out

2021-11-03T01:50:24.253 full_node full_node_server        : ERROR    Exception: Failed to fetch block 394064 from None, timed out <class 'ValueError'>, closing connection None. Traceback (most recent call last):
  File "achi\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "achi\server\server.py", line 533, in wrapped_coroutine
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 394064 from None, timed out

2021-11-03T07:53:41.795 full_node full_node_server        : WARNING  Cannot write to closing transport 170.249.236.56
2021-11-03T08:26:36.746 harvester achi.plotting.plot_tools: ERROR    Failed to open file H:\plots\plot-k32-2021-11-02-20-18-f8c501893291f586f5294abf58609191eb993fd779d067eb3315e48a4baaef58.plot. Invalid file H:\plots\plot-k32-2021-11-02-20-18-f8c501893291f586f5294abf58609191eb993fd779d067eb3315e48a4baaef58.plot Traceback (most recent call last):
  File "achi\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file H:\plots\plot-k32-2021-11-02-20-18-f8c501893291f586f5294abf58609191eb993fd779d067eb3315e48a4baaef58.plot

2021-11-03T08:47:29.913 harvester achi.plotting.plot_tools: ERROR    Failed to open file H:\plots\plot-k32-2021-11-02-23-49-c78de8a1df386102e0e94957b6f60efdbf608e21aa63396401eff3e93b88c1e6.plot. Invalid file H:\plots\plot-k32-2021-11-02-23-49-c78de8a1df386102e0e94957b6f60efdbf608e21aa63396401eff3e93b88c1e6.plot Traceback (most recent call last):
  File "achi\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file H:\plots\plot-k32-2021-11-02-23-49-c78de8a1df386102e0e94957b6f60efdbf608e21aa63396401eff3e93b88c1e6.plot

2021-11-03T09:06:13.102 harvester achi.plotting.plot_tools: ERROR    Failed to open file H:\plots\plot-k32-2021-11-03-03-24-2dc843a6244f085ac02c498699396cce8b7bbe2ffe9da93a26c213e1e5fac17e.plot. Invalid file H:\plots\plot-k32-2021-11-03-03-24-2dc843a6244f085ac02c498699396cce8b7bbe2ffe9da93a26c213e1e5fac17e.plot Traceback (most recent call last):
  File "achi\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file H:\plots\plot-k32-2021-11-03-03-24-2dc843a6244f085ac02c498699396cce8b7bbe2ffe9da93a26c213e1e5fac17e.plot

2021-11-03T11:25:21.064 harvester achi.plotting.plot_tools: ERROR    Failed to open file H:\plots\plot-k32-2021-11-03-07-01-a0987078f441c44c4990c9a180284ee091a2564bccbd672f7c17d474b432b273.plot. Invalid file H:\plots\plot-k32-2021-11-03-07-01-a0987078f441c44c4990c9a180284ee091a2564bccbd672f7c17d474b432b273.plot Traceback (most recent call last):
  File "achi\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file H:\plots\plot-k32-2021-11-03-07-01-a0987078f441c44c4990c9a180284ee091a2564bccbd672f7c17d474b432b273.plot

2021-11-03T11:45:55.549 harvester achi.plotting.plot_tools: ERROR    Failed to open file H:\plots\plot-k32-2021-11-03-07-01-a0987078f441c44c4990c9a180284ee091a2564bccbd672f7c17d474b432b273.plot. Invalid file H:\plots\plot-k32-2021-11-03-07-01-a0987078f441c44c4990c9a180284ee091a2564bccbd672f7c17d474b432b273.plot Traceback (most recent call last):
  File "achi\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file H:\plots\plot-k32-2021-11-03-07-01-a0987078f441c44c4990c9a180284ee091a2564bccbd672f7c17d474b432b273.plot

2021-11-03T13:11:18.197 full_node achi.full_node.full_node: ERROR    Respond peers exception: 'NoneType' object has no attribute 'host'. Traceback: Traceback (most recent call last):
  File "achi\server\node_discovery.py", line 572, in respond_peers
  File "achi\server\node_discovery.py", line 537, in add_peers_neighbour
AttributeError: 'NoneType' object has no attribute 'host'

2021-11-03T18:39:32.068 full_node full_node_server        : ERROR    Exception: Failed to fetch block 397606 from {'host': '73.202.252.38', 'port': 9975}, timed out, {'host': '73.202.252.38', 'port': 9975}. Traceback (most recent call last):
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 397606 from {'host': '73.202.252.38', 'port': 9975}, timed out

2021-11-03T18:39:32.070 full_node full_node_server        : ERROR    Exception: Failed to fetch block 397606 from {'host': '73.202.252.38', 'port': 9975}, timed out <class 'ValueError'>, closing connection {'host': '73.202.252.38', 'port': 9975}. Traceback (most recent call last):
  File "achi\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "achi\server\server.py", line 533, in wrapped_coroutine
  File "achi\server\server.py", line 526, in wrapped_coroutine
  File "achi\full_node\full_node_api.py", line 105, in new_peak
  File "achi\full_node\full_node.py", line 372, in new_peak
  File "achi\full_node\full_node.py", line 322, in short_sync_backtrack
  File "achi\full_node\full_node.py", line 307, in short_sync_backtrack
ValueError: Failed to fetch block 397606 from {'host': '73.202.252.38', 'port': 9975}, timed out

2021-11-03T18:39:42.105 full_node full_node_server        : WARNING  Banning 73.202.252.38 for 10 seconds
2021-11-03T18:54:09.864 full_node achi.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "achi\rpc\rpc_server.py", line 212, in safe_handle
  File "achi\rpc\rpc_server.py", line 200, in ws_api
  File "achi\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-11-03T18:54:20.004 full_node achi.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "achi\rpc\rpc_server.py", line 212, in safe_handle
  File "achi\rpc\rpc_server.py", line 200, in ws_api
  File "achi\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-11-03T18:59:18.846 full_node achi.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "achi\rpc\rpc_server.py", line 212, in safe_handle
  File "achi\rpc\rpc_server.py", line 200, in ws_api
  File "achi\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-11-03T18:59:51.398 full_node achi.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "achi\rpc\rpc_server.py", line 212, in safe_handle
  File "achi\rpc\rpc_server.py", line 200, in ws_api
  File "achi\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-11-03T19:00:19.655 full_node full_node_server        : ERROR    Exception wss://95.67.41.4::9975/ws, exception Stack: Traceback (most recent call last):
  File "yarl\_url.py", line 170, in __new__
  File "urllib\parse.py", line 178, in port
ValueError: Port could not be cast to integer value as ':9975'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aiohttp\client.py", line 404, in _request
  File "yarl\_url.py", line 172, in __new__
ValueError: Invalid URL: port can't be converted to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "achi\server\server.py", line 360, in start_client
  File "aiohttp\client.py", line 754, in _ws_connect
  File "aiohttp\client.py", line 406, in _request
aiohttp.client_exceptions.InvalidURL: wss://95.67.41.4::9975/ws

2021-11-03T19:00:19.656 full_node achi.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "achi\rpc\rpc_server.py", line 212, in safe_handle
  File "achi\rpc\rpc_server.py", line 200, in ws_api
  File "achi\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-11-03T19:04:26.263 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA621414F0>
2021-11-03T19:04:26.264 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA605D47F0>
2021-11-03T19:04:26.265 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA5F85FF40>
2021-11-03T19:04:26.266 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA618B3760>
2021-11-03T19:04:26.267 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA5FCB68B0>
2021-11-03T19:04:26.271 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA5FE40CD0>
2021-11-03T19:04:26.272 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA618B6B50>
2021-11-03T19:04:26.273 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA61B9E1F0>
2021-11-03T19:04:26.273 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA5F5F2910>
2021-11-03T19:04:26.274 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA5DB74520>

**Comment by coolpro313** [comment]
facing the same issue too the only way that i was able to temporarily fix the issue was just deleting the blockchain and redownload the entire chain but dont want to keep doing that everytime when i restart my PC either from a power outage or a windows update

**Comment by Achi-Coin** [comment]
reinstall achi from scretch
