### ISSUE TITLE
 LookupError: setuptools-scm was unable to detect version for '/home/server/achi-blockchain-1.0.1'.

### ISSUE THREAD

**Issue by arcanis2k3** [Achi-Coin/achi-blockchain#4]
Not able to finish install.sh

$ python -m pip install -e . --extra-index-url https://pypi.achicoin.org/simple/Looking in indexes: https://pypi.org/simple, https://pypi.achicoin.org/simple/

Obtaining file:///home/server/achi-blockchain-1.0.1
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/server/achi-blockchain-1.0.1/venv/bin/python /home/server/achi-blockchain-1.0.1/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpcblb0v6n
       cwd: /home/server/achi-blockchain-1.0.1
  Complete output (36 lines):
  Traceback (most recent call last):
    File "/home/server/achi-blockchain-1.0.1/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/server/achi-blockchain-1.0.1/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/server/achi-blockchain-1.0.1/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 117, in <module>
      setup(**kwargs)
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 455, in __init__
      _Distribution.__init__(self, {
    File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 807, in finalize_options
      ep(self)
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 59, in infer_version
      dist.metadata.version = _get_version(config)
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
      parsed_version = _do_parse(config)
    File "/tmp/pip-build-env-r1vsyzyu/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 134, in _do_parse
      raise LookupError(
  LookupError: setuptools-scm was unable to detect version for '/home/server/achi-blockchain-1.0.1'.

  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

  For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
  ----------------------------------------
WARNING: Discarding file:///home/server/achi-blockchain-1.0.1. Command errored out with exit status 1: /home/server/achi-blockchain-1.0.1/venv/bin/python /home/server/achi-blockchain-1.0.1/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpcblb0v6n Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/server/achi-blockchain-1.0.1/venv/bin/python /home/server/achi-blockchain-1.0.1/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpcblb0v6n Check the logs for full command output.

**Comment by Achi-Coin** [comment]
Please follow instruction from https://achicoin.org

**Comment by Achi-Coin** [comment]
# First Install Ubuntu 20.04 https://ubuntu.com
# Open the terminal and update the package list:
sudo apt update
sudo apt upgrade

# Install Git:
sudo apt install git -y

# Checkout the source and install:
git clone https://github.com/Achi-Coin/achi-blockchain
cd achi-blockchain

sh install.sh
. ./activate
achi init

**Comment by Achi-Coin** [comment]
\# First Install Ubuntu 20.04 https://ubuntu.com
\# Open the terminal and update the package list:
sudo apt update
sudo apt upgrade

\# Install Git:
sudo apt install git -y

\# Checkout the source and install:
git clone https://github.com/Achi-Coin/achi-blockchain
cd achi-blockchain
sh install.sh
. ./activate
achi init
